name: Publish Sonatype Stats to GitHub Pages

on:
  push:
    branches:
      - master
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 7,15 * *'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Cache fetched data
        uses: actions/cache@v4
        with:
          path: data
          key: setup-1

      - name: Fetch and render Sonatype Stats
        uses: MateuszKubuszok/sonatype-stats@v1.0.0
        with:
          sonatype-project: ${{ vars.SONATYPE_PROJECT }}
          sonatype-username: ${{ secrets.SONATYPE_USERNAME }}
          sonatype-password: ${{ secrets.SONATYPE_PASSWORD }}

      - name: Publish generated content to GitHub Pages
        uses: tsunematsu21/actions-publish-gh-pages@v1.0.2
        with:
          dir: data
          branch: gh-pages
          token: ${{ secrets.ACCESS_TOKEN }}

